Repository watermelontools/watermelon, pull requests merged in 2023-10, with the labels that each got.

#323 Extract functions and texts
  utils/actions/labelPullRequest.ts
Labels: 🍉 Safe to Merge

#324 Detect console.logs and its equivalent in other languages
  app/api/actions/github/route.ts
  utils/actions/detectConsoleLogs.ts
  utils/actions/labelPullRequest.ts
Labels: 👀 Take a deeper dive

#321 Improve prompt to make AI summaries on GitHub app more concise
  utils/actions/getOpenAISummary.ts
Labels: 👀 Take a deeper dive

#331 Feature/comment specific line diffs
  utils/actions/detectConsoleLogs.ts
Labels: 🚨 Don't Merge

#353 Fix/broken login getting
  app/api/actions/github/route.ts
Labels: 👀 Take a deeper dive

#352 Chore/readme update messaging and strategy
  README.md
Labels: 🚨 Don't Merge

#355 v2.1.2
  README.md
  app/api/actions/github/route.ts
  utils/actions/detectConsoleLogs.ts
Labels: 🚨 Don't Merge
