Repository watermelontools/watermelon, pull requests merged in 2023-11, with the labels that each got.

#359 Fix/add catches to octokit
  utils/actions/detectConsoleLogs.ts
  utils/actions/labelPullRequest.ts
Labels: 🍉 Safe to Merge

#358 Fix/missing params when a comment is created or edited
  app/api/actions/github/route.ts
Labels: 🍉 Safe to Merge

#357 Delete public/favicon_io.zip
  public/favicon_io.zip
Labels: 🍉 Safe to Merge

#360 v2.1.3
  app/api/actions/github/route.ts
  public/favicon_io.zip
  utils/actions/detectConsoleLogs.ts
  utils/actions/labelPullRequest.ts
Labels: 🚨 Don't Merge

#361 Delete public/questionsHappyTulia.png
  public/questionsHappyTulia.png
Labels: 🍉 Safe to Merge

#362 Bugfix: Remove duplicate PR comments
  app/api/actions/github/route.ts
Labels: 👀 Take a deeper dive

#365 Update model to GPT4-turbo
  utils/actions/getOpenAISummary.ts
Labels: 🍉 Safe to Merge

#370 Pin Next version to 13
  package.json
Labels: 🍉 Safe to Merge

#367 Add the ruby case, and add the [input=email] string as a counter example
  utils/actions/detectConsoleLogs.ts
Labels: 🍉 Safe to Merge

#375 Make calls to other services concurrent
  app/api/actions/github/route.ts
Labels: 👀 Take a deeper dive

#377 Fix/prevent double console log commenting
  utils/actions/detectConsoleLogs.ts
Labels: 🍉 Safe to Merge

#387 Create dependabot.yml
  .github/dependabot.yml
Labels: 🍉 Safe to Merge

#384 Fix undefined team url
  app/(loggedIn)/team/sendInviteForm.tsx
Labels: 👀 Take a deeper dive

#386 Bugfix - Multiple PR commenting
  README.md
  app/(loggedIn)/loading.tsx
  app/(notLogged)/auth/verify/page.tsx
  app/api/actions/github/route.ts
  app/github-app/page.ts
  components/Header.tsx
  components/login-btn.tsx
Labels: 🍉 Safe to Merge

#389 REmove commons clause
  LICENSE
Labels: 👀 Take a deeper dive

#390 Chore/remove unused pieces
  app/(loggedIn)/page.tsx
  components/Header.tsx
  components/loginGrid.tsx
  utils/actions/markdownHelpers/randomText.ts
Labels: 🍉 Safe to Merge

#388 Bugfix - Deactivate comenting on bot PRs
  app/api/actions/github/route.ts
Labels: 🍉 Safe to Merge

#380 v2.1.4
  .github/dependabot.yml
  LICENSE
  README.md
  app/(loggedIn)/loading.tsx
  app/(loggedIn)/page.tsx
  app/(loggedIn)/team/sendInviteForm.tsx
  app/(notLogged)/auth/verify/page.tsx
  app/api/actions/github/route.ts
  app/github-app/page.ts
  components/Header.tsx
  components/login-btn.tsx
  components/loginGrid.tsx
  package.json
  public/questionsHappyTulia.png
  utils/actions/detectConsoleLogs.ts
  utils/actions/getOpenAISummary.ts
  utils/actions/markdownHelpers/randomText.ts
  utils/sendgrid/sendUninstall.ts
Labels: 👀 Take a deeper dive

#395 Bugfix/new counter
  utils/api/updateGitHubCounts.ts
  utils/db/github/updateGitHubQueryCounts.ts
  utils/db/teams/addActionCount.ts
  vercel.json
Labels: 👀 Take a deeper dive
